version: "3.9"

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PROJECTDIR}:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
  php:
    build:
      context: ./php-fpm
    volumes:
      - ${PROJECTDIR}:/var/www/html
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: on-failure
    environment:
      MYSQL_DATABASE: dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: docker